"""add_rental_and_sale_fields_to_listings

Revision ID: a492fc2167c1
Revises: b2c3d4e5f6a7
Create Date: 2026-07-09 19:56:20.805943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a492fc2167c1'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create missing rental tables
    op.create_table('rental_listings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('listing_id', sa.Integer(), nullable=False),
        sa.Column('rental_hourly_rate', sa.Float(), nullable=True),
        sa.Column('rental_daily_rate', sa.Float(), nullable=True),
        sa.Column('rental_weekly_rate', sa.Float(), nullable=True),
        sa.Column('rental_monthly_rate', sa.Float(), nullable=True),
        sa.Column('security_deposit', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('delivery_fee', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('cleaning_fee', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('insurance_fee', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('late_return_fee_rate', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('status', sa.String(), nullable=False, server_default='Active'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('rental_bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('listing_id', sa.Integer(), nullable=False),
        sa.Column('buyer_id', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='Pending'),
        sa.Column('total_cost', sa.Float(), nullable=False),
        sa.Column('instant_book', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('rental_calendar',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('listing_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('seasonal_price_override', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('rental_contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('terms_text', sa.Text(), nullable=False),
        sa.Column('signature_status', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('signed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['rental_bookings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('rental_deposits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('amount_held', sa.Float(), nullable=False),
        sa.Column('deduction_amount', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('status', sa.String(), nullable=False, server_default='Held'),
        sa.ForeignKeyConstraint(['booking_id'], ['rental_bookings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('rental_returns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('inspector_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='Returned'),
        sa.Column('damage_cost', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('inspection_notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['rental_bookings.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('allow_sale', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('listings', sa.Column('allow_rental', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('notifications', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_rental_bookings_buyer_id'), 'rental_bookings', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_rental_bookings_id'), 'rental_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_rental_bookings_listing_id'), 'rental_bookings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_rental_calendar_date'), 'rental_calendar', ['date'], unique=False)
    op.create_index(op.f('ix_rental_calendar_id'), 'rental_calendar', ['id'], unique=False)
    op.create_index(op.f('ix_rental_calendar_listing_id'), 'rental_calendar', ['listing_id'], unique=False)
    op.create_index(op.f('ix_rental_contracts_booking_id'), 'rental_contracts', ['booking_id'], unique=False)
    op.create_index(op.f('ix_rental_contracts_id'), 'rental_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_rental_deposits_booking_id'), 'rental_deposits', ['booking_id'], unique=False)
    op.create_index(op.f('ix_rental_deposits_id'), 'rental_deposits', ['id'], unique=False)
    op.create_index(op.f('ix_rental_listings_id'), 'rental_listings', ['id'], unique=False)
    op.create_index(op.f('ix_rental_listings_listing_id'), 'rental_listings', ['listing_id'], unique=True)
    op.create_index(op.f('ix_rental_returns_booking_id'), 'rental_returns', ['booking_id'], unique=False)
    op.create_index(op.f('ix_rental_returns_id'), 'rental_returns', ['id'], unique=False)
    op.create_index(op.f('ix_rental_returns_inspector_id'), 'rental_returns', ['inspector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_returns_inspector_id'), table_name='rental_returns')
    op.drop_index(op.f('ix_rental_returns_id'), table_name='rental_returns')
    op.drop_index(op.f('ix_rental_returns_booking_id'), table_name='rental_returns')
    op.drop_index(op.f('ix_rental_listings_listing_id'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_listings_id'), table_name='rental_listings')
    op.drop_index(op.f('ix_rental_deposits_id'), table_name='rental_deposits')
    op.drop_index(op.f('ix_rental_deposits_booking_id'), table_name='rental_deposits')
    op.drop_index(op.f('ix_rental_contracts_id'), table_name='rental_contracts')
    op.drop_index(op.f('ix_rental_contracts_booking_id'), table_name='rental_contracts')
    op.drop_index(op.f('ix_rental_calendar_listing_id'), table_name='rental_calendar')
    op.drop_index(op.f('ix_rental_calendar_id'), table_name='rental_calendar')
    op.drop_index(op.f('ix_rental_calendar_date'), table_name='rental_calendar')
    op.drop_index(op.f('ix_rental_bookings_listing_id'), table_name='rental_bookings')
    op.drop_index(op.f('ix_rental_bookings_id'), table_name='rental_bookings')
    op.drop_index(op.f('ix_rental_bookings_buyer_id'), table_name='rental_bookings')
    op.drop_column('notifications', 'is_archived')
    op.drop_column('listings', 'allow_rental')
    op.drop_column('listings', 'allow_sale')
    # ### end Alembic commands ###

    # Drop missing rental tables
    op.drop_table('rental_returns')
    op.drop_table('rental_deposits')
    op.drop_table('rental_contracts')
    op.drop_table('rental_calendar')
    op.drop_table('rental_bookings')
    op.drop_table('rental_listings')
